drop table if exists users cascade;
drop table if exists items cascade;
drop table if exists bookings cascade;
drop table if exists requests cascade;
drop table if exists comments cascade;

create table if not exists users (
                                     user_id    bigint generated by default as identity not null
                                     constraint users_pk primary key,
                                     user_name  varchar(255) not null,
    user_email varchar(255) not null,
    UNIQUE (user_email)
    );

create table if not exists item_request (
                                        item_request_id            bigint generated by default as identity not null
                                        constraint requests_pk primary key,
                                        item_request_description   varchar(2000) not null,
    requestor_id  bigint        not null
    constraint requests_users_id_fk references users,
    created date          not null
    );

create table if not exists items (
                                     item_id         bigint generated by default as identity not null
                                     constraint items_pk primary key,
                                     item_name        varchar(255)  not null,
    item_description varchar(2000) not null,
    item_available   boolean       not null,
    item_owner_id    integer       not null
    constraint items_users_id_fk references users,
    item_request_id     integer
    );

create table if not exists booking (
                                       booking_id         bigint generated by default as identity not null
                                        constraint bookings_pk primary key,
                                       booking_item_id    bigint      not null
                                        constraint bookings_items_id_fk references items,
                                        book_start_date timestamp        not null,
                                        book_end_date   timestamp        not null,
                                       booker_id    bigint      not null
                                        constraint bookings_users_id_fk references users,
                                        book_status     varchar(50) not null
    );
create table if not exists comments (
                                        comment_id        bigint generated by default as identity not null
                                        constraint comments_pk primary key,
                                        comment_item_id   bigint        not null
                                        constraint comments_items_id_fk references items,
                                        comment_user_id bigint        not null
                                        constraint comments_users_id_fk references users,
                                        comment_text      varchar(2000) not null,
    comment_created     timestamp    not null
    );



